### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by bismosa** [HomeAutoUser/Jaro#3]
BUGS:
- [ ] UI Einzeilig ohne addGroups -> ERROR: your command OptionValue is not support! (not in list)
Zeile: `return "ERROR: your command $cmd is not support! (not in list)" if ($ret !~ /$cmd/ && $addGroups eq "");`
- [ ] Gerät ohne IODEV - PERL Fehler beheben
`define SD_JARO_Device1 SD_JARO 12345678 JaroLift`
Werden keine Attribute und kein IODEV gesetzt.

ToDo:
- [ ] Buttoncode "Learn" ändern (siehe Pull Request)
- [ ] Neue und alte Lernmethode integrieren
alt = jetziger Buttoncode
neu = updown gefolgt von stop
- [ ] Shade learn
4xSTOP (jedes Mal neuer Code!)
- [ ] Shade integrieren
20x STOP
- [ ] Updates Module: 
00_SIGNALduino.pm 
signalduino_protocols.hash
- [ ] Updates Firmware
- [ ] rekonstruktion des letzten fehlenden Bits
- [ ] Verbose Level für Logs anpassen (einige noch unter "3")
- [ ] Doku Deutsch überarbeiten
- [ ] Doku Englisch übersetzen

Diskutieren / Offene Diskussion:
- [ ] Sende-Counter: Als Reading oder z.B. in eine Datei (Damit bei einem außerplanmäßigem FHEM-Neustart die Werte erhalten bleiben (?)
- [ ] MSB/LSB/KeeloqNLF in geschütztem Speicher (?)
- [ ] Umbenennen JARO -> Rollo (?)

Tests:
- [ ] Testen, mit welchen Codes das Lernen erfolgreich ist
- [ ] UI Komplett testen

Wünsche:
- [ ] ...

Vorschläge
- [ ] UI anzeigen, sobald MSB LSB + NLF gesetzt sind?

**Comment by HomeAutoUser** [comment]
@bismosa das ist eine gute Idee mit dem Faden.
Bitte wenn wir einen Verweis haben auf einen bestimmten Post hier, dann den Link mal mit hinzufügen in der Liste oben, so findet man es schneller.

Ich würde mich als erstes mal dem 
* Buttoncode "Learn" ändern (siehe Pull Request)

widmen und dann ggf
* Neue und alte Lernmethode integrieren
      alt = jetziger Buttoncode
      neu = updown gefolgt von stop

**Comment by bismosa** [comment]
Hallo,

@HomeAutoUser 
Bitte fertiges lieber abhaken statt zu löschen. Dann wissen wir besser, was auch getestet werden muss...

Ich hatte gerade die Links alle eingefügt..da aber zwischendurch geändert wurde wurde meine Änderung verworfen...naja...dann halt nochmal..edit folgt gleich

Gruß
Bismosa

**Comment by bismosa** [comment]
> EDIT:
> **Verständnisfrage:**
> 
> * Shade learn
>   4xSTOP (jedes Mal neuer Code!)
> * Shade integrieren
>   20x STOP

Shade learn:
4x nacheinander Stop auf der Fernbedienung betätigen. Also jedes Mal ein neuen Code generieren und Senden

Shade anfahren:
20x STOP senden. Ohne Änderung des Codes. Also mit 20 Sendewiederholungen

Gruß
Bismosa

**Comment by HomeAutoUser** [comment]
@bismosa ,
ich lösche nichts hier :-D Wir haben uns zeitlich nur überschnitten!

**Comment by bismosa** [comment]
Huhu :-)

> ich lösche nichts hier :-D Wir haben uns zeitlich nur überschnitten!

Stimmt. Mein Fehler. Habe die Änderungseintragung falsch gedeutet Sorry :-)

Gruß
Bismosa

**Comment by HomeAutoUser** [comment]
@bismosa 
```
Shade learn:
4x nacheinander Stop auf der Fernbedienung betätigen. Also jedes Mal ein neuen Code generieren und Senden

Shade anfahren:
20x STOP senden. Ohne Änderung des Codes. Also mit 20 Sendewiederholungen
```

Da gibt es die Codes nicht fest ? Also ich verweise auf das Nibble7 welches dort einen festen Wert je tastendruck hat. ODER sind Shade + Shadelearn nur eine Abfolge von Befehlen Stop.
Also
**Shade learn:**
4x Stop gedrückt auf der FB, so das jedesmal ein neuer Code inkl. Zähler generiert wird

**Shade:**
20x Sendewiederholungen des Stop Befehles?

**Comment by bismosa** [comment]
> Da gibt es die Codes nicht fest ? Also ich verweise auf das Nibble7 welches dort einen festen Wert je tastendruck hat. ODER sind Shade + Shadelearn nur eine Abfolge von Befehlen Stop.

Nein. Diese Taste existiert überhaupt nicht. Das ist nur eine Funktion die aufgerufen wird durch eine Abfolge von Befehlen.
`"shade"			=>	"0101", #Diesen Code gibt es so nicht`
Ich habe keine Ahnung, wie wir mal auf diesen Code gekommen sind. Habe die Ahnung, dass ich es damals mit hinzugefügt hatte und selbst noch nicht wusste, wie das funktioniert...

Ausprobieren kann ich diese Funktion auch leider nicht. Meine Rolläden unterstützen dies nicht. 
Daher können wir leider auch keine Daten dafür sammeln...

> **Shade learn:**
> 4x Stop gedrückt auf der FB, so das jedesmal ein neuer Code inkl. Zähler generiert wird
> 
> **Shade:**
> 20x Sendewiederholungen des Stop Befehles?

Genau richtig :-)

Gruß
Bismsoa

**Comment by HomeAutoUser** [comment]
@bismosa 

>    * [ ]  UI anzeigen, sobald MSB LSB + NLF gesetzt sind?

den Punkt würde ich so belassen und nicht anders.
Das UI wurde für JaroLift angefertigt und ob es komplett bei Roto ebensogeht ist nicht derzeit sicherzustellen. Hinzu kommt, das wir so keinem User ein UI "aufzwingen". Die Option einstellbar von selbst ist schon der richtige Weg denke ich. Somit würde ich von der Automatik absehen.

**Comment by HomeAutoUser** [comment]
Grüßt Euch auf dieser Ebene :-)
Läuft bei euch das modul noch bestens?

Haben wir noch Anpassungen oder Hinweise in der Commandref offen?
Wollte mir mal einen Überblick verschaffen.

MfG

**Comment by D3ltorohd** [comment]
Hi @HomeAutoUser das Modul läuft bis jetzt PERFEKT, keine einzige Fahrt wurde ausgelassen, die Rollos reagieren sofort. Anders als bei meinen original Wandsendern.
Also hier läuft das Modul bestens !!

Zum rest kann ich leidern nichts sagen ;-) Hab zwecks dem Modul gar nie in die Commandreg geschaut

Grüße und besten Dank für das geniale Modul für die Jaro's !

**Comment by bismosa** [comment]
Hallo!
Kann mich fast anschließen. Einfach ein tolles Modul ohne nennenswerte Schwierigkeiten.
Leider kommt es immer mal wieder vor, das ein Rolladen nicht fahren will. Etwas besser ist es geworden nachdem ich die Sendewiederholungen hochgeschraubt habe. 
Ob dies nun an meiner Antennentechnik, dem CUL oder dem Raspberry der sehr viele Aufgaben zu erledigen hat liegt weiß ich nicht. Aber bei den anderen Lösungen hatte ich häufiger aussetzer.

Also ich bin ebenfalls sehr sehr zufrieden!! :) 

Es sind ja eigentlich noch ein paar Kleinigkeiten auf der ToDo liste. Ich denke aber, dass wir das zumindest vorerst ignorieren können...es gab soweit ich es weiß ja keine Beschwerden :)

Gruß
Bismosa

**Comment by HomeAutoUser** [comment]
Hallo @bismosa 
gern können wir die Punkte der Liste mal ansehen und schauen ob wir da handeln oder dies als erledigt betrachten. Die Entwicklung - Verfeinerung geht ja ständig weiter :-)

MfG

**Comment by bismosa** [comment]
Hallo!

Klar gerne :) ...jedoch ist gerade die Urlaubszeit und meine Privatzeit etwas knapp.

> Spaltenbreite teilweise fehlerhaft / Fixe breite setzen? 

Dies ist ein Punkt, den ich noch im Developer-Board klären wollte. Ich habe bei einem anderen Modul von mir das gleiche "Problem". Das habe ich aber etwas nach hinten geschoben...

> Updates Firmware (#1 (comment)) (#1 (comment))
>   rekonstruktion des letzten fehlenden Bits (#1 (comment))
>   Verbose Level für Logs anpassen (einige noch unter "3") (#1 (comment))
>   Doku Deutsch überarbeiten
>   Doku Englisch übersetzen

>   UI Komplett testen

Ich glaube diese Punkte sind alle erledigt?

> Sende-Counter: Als Reading oder z.B. in eine Datei (Damit bei einem außerplanmäßigem FHEM-Neustart die Werte erhalten bleiben (?)
>   MSB/LSB/KeeloqNLF in geschütztem Speicher (?)

Gibt es in FHEM denn einen "geschützten Speicher" wo diese Werte abgelegt werden könnten? Ich kenne nur internals mit einem Punkt vorweg. Diese sind bei einem List-Device aber immer noch sichtbar.

>  Testen, mit welchen Codes das Lernen erfolgreich ist (#1 (comment))

Ich weiß gerade gar nicht mehr den aktuellen Stand...aber ich glaube wir hatten da mal irgendwann aufgehört...

> Symbole anpassbar

Könnte man über Attribute machen...

Gruß
Bismosa
